# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abd89d3e7af0c7cf0c0467c5670b9cb30b1a21115f51976e851e4e1b855e3b68693a444d3a4328c3050549562da931ce341fa38e1825a0a100aa393298757b44

test:
  secret_key_base: f86bfeda533a5d29acd3c942a9ecce1c8565c62d5d41a07f59ad90882cbcdabd921b7e97cfce9e0b6940f84bbde50ba23fcb1b3641b9985cf1ba83571488c8d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
